import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          background: "#fff",
        }}
      >
        <h1 style={{ fontSize: "4rem", margin: 0 }}>
          Welcome to{" "}
          <a
            href="https://nextjs.org"
            style={{ color: "#0070f3", textDecoration: "none" }}
          >
            Next.js!
          </a>
        </h1>
        <p style={{ fontSize: "1.5rem", marginTop: "2rem" }}>
          Get started by editing&nbsp;
          <code
            style={{
              background: "#f5f5f5",
              padding: "0.2em 0.4em",
              borderRadius: "4px",
            }}
          >
            pages/index.tsx
          </code>
        </p>
        <div style={{ marginTop: "3rem", display: "flex", gap: "2rem" }}>
          <a
            href="https://nextjs.org/docs"
            style={{
              padding: "1.5rem",
              border: "1px solid #eaeaea",
              borderRadius: "10px",
              textDecoration: "none",
              color: "inherit",
              transition: "color 0.15s ease, border-color 0.15s ease",
            }}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={{ margin: 0, marginBottom: "1rem" }}>Docs &rarr;</h2>
            <p style={{ margin: 0 }}>
              Find in-depth information about Next.js features and API.
            </p>
          </a>
          <a
            href="https://nextjs.org/learn"
            style={{
              padding: "1.5rem",
              border: "1px solid #eaeaea",
              borderRadius: "10px",
              textDecoration: "none",
              color: "inherit",
              transition: "color 0.15s ease, border-color 0.15s ease",
            }}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={{ margin: 0, marginBottom: "1rem" }}>Learn &rarr;</h2>
            <p style={{ margin: 0 }}>
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}
